export const countriesData = [
  { label: "Australia", value: "AU", flag: "🇦🇺" },
  { label: "Brazil", value: "BR", flag: "🇧🇷" },
  { label: "Canada", value: "CA", flag: "🇨🇦" },
  { label: "Switzerland", value: "CH", flag: "🇨🇭" },
  { label: "Germany", value: "DE", flag: "🇩🇪" },
  { label: "Denmark", value: "DK", flag: "🇩🇰" },
  { label: "Spain", value: "ES", flag: "🇪🇸" },
  { label: "Finland", value: "FI", flag: "🇫🇮" },
  { label: "France", value: "FR", flag: "🇫🇷" },
  { label: "United Kingdom", value: "GB", flag: "🇬🇧" },
  { label: "Ireland", value: "IE", flag: "🇮🇪" },
  { label: "India", value: "IN", flag: "🇮🇳" },
  { label: "Iran", value: "IR", flag: "🇮🇷" },
  { label: "Mexico", value: "MX", flag: "🇲🇽" },
  { label: "Netherlands", value: "NL", flag: "🇳🇱" },
  { label: "Norway", value: "NO", flag: "🇳🇴" },
  { label: "New Zealand", value: "NZ", flag: "🇳🇿" },
  { label: "Serbia", value: "RS", flag: "🇷🇸" },
  { label: "Turkey", value: "TR", flag: "🇹🇷" },
  { label: "Ukraine", value: "UA", flag: "🇺🇦" },
  { label: "United States", value: "US", flag: "🇺🇸" }
];
