export const countriesData = [
  { label: "AU", value: "AU" },
  { label: "BR", value: "BR" },
  { label: "CA", value: "CA" },
  { label: "CH", value: "CH" },
  { label: "DE", value: "DE" },
  { label: "DK", value: "DK" },
  { label: "ES", value: "ES" },
  { label: "FI", value: "FI" },
  { label: "FR", value: "FR" },
  { label: "GB", value: "GB" },
  { label: "IE", value: "IE" },
  { label: "IN", value: "IN" },
  { label: "IR", value: "IR" },
  { label: "MX", value: "MX" },
  { label: "NL", value: "NL" },
  { label: "NO", value: "NO" },
  { label: "NZ", value: "NZ" },
  { label: "RS", value: "RS" },
  { label: "TR", value: "TR" },
  { label: "UA", value: "UA" },
  { label: "US", value: "US" }
];
